version: '2.1'

services:
  data:
    build: jenkins-data
    image: mikeder/jenkins-data
  master:
    build: jenkins-master
    image: mikeder/jenkins-master
    volumes_from:
      - data
    volumes:
      - ./jenkinslocation.txt:/myfiles/jenkinslocation.txt
    ports:
      - "50000:50000"
  nginx:
    build: jenkins-nginx
    image: mikeder/jenkins-nginx
    ports:
      - "80:80"
    links:
      - master:jenkins-master
  slave:
    build:
      context: jenkins-slave
      args:
        - host_docker_group=999
        - host_docker_version=17.09
    image: mikeder/jenkins-slave
  proxy:
    image: ehazlett/docker-proxy:latest
    command: -i
    ports:
      - "3375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

